Repository OsushiGeekCamp/openai-finetuning-helper, pull requests merged in 2023-10, with the labels that each got.

#3 add GitHub Workflows: build & deploy
  .github/workflows/gh-pages.yml
  for-github-workflows.next.config.js
Labels: CI/CD

#5 [gh-pages workflow] Remove pull_request trigger
  .github/workflows/gh-pages.yml
Labels: CI/CD

#7 [gh-pages workflow] Migrate to pnpm/action-setup for installation
  .github/workflows/gh-pages.yml
Labels: CI/CD

#9 Integrate Prettier for Consistent Code Formatting
  .github/workflows/gh-pages.yml
  .prettierignore
  .prettierrc
  next.config.js
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: enhancement

#11 Integrate lint-staged for Pre-commit Linting and Formatting
  lint-staged.config.js
  package.json
  pnpm-lock.yaml
Labels: enhancement

#13 Integrate husky for Enhanced Git Hooks Management
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: enhancement

#15 add GitHub Workflows: lint
  .github/workflows/lint.yml
Labels: CI/CD

#22 Create a utility function for fetching files from the API
  src/utils/api.ts
Labels: enhancement

#24 Add ToggleSwitch Component
  src/components/toggle-switch.tsx
Labels: enhancement

#26 Improve Accessibility for ToggleSwitch Component
  src/components/toggle-switch.tsx
Labels: enhancement

#29 Add Loading Component
  src/components/loading.tsx
Labels: enhancement

#27 Display List of Uploaded Files on OpenAI
  src/app/file-list/page.tsx
Labels: enhancement

#31 Refactoring ToggleSwitch Component for Better Readability and Consistency
  src/components/toggle-switch.tsx
Labels: enhancement

#32 change Licence
  LICENSE.txt
Labels: documentation

#36 Create a page to edit fine-tuning dataset
  src/app/editor/components/button.tsx
  src/app/editor/components/editor-page.tsx
  src/app/editor/components/example-list.tsx
  src/app/editor/components/header.tsx
  src/app/editor/components/message-form.tsx
  src/app/editor/components/message-list.tsx
  src/app/editor/containers/editor-page.tsx
  src/app/editor/page.tsx
  src/app/editor/reducers/examples.ts
  src/types/example.ts
  src/types/message.ts
  src/types/role.ts
  src/utils/clipboard.ts
Labels: enhancement

#38 Type conflict with Next.js implicit types in Editor component
  src/app/editor/page.tsx
Labels: bug

#40 Enhance ToggleSwitch Component for Better Dark Mode Support
  src/components/toggle-switch.tsx
Labels: enhancement

#44 UI Spacing Adjustments in Editor Components
  src/app/editor/components/editor-page.tsx
  src/app/editor/components/message-form.tsx
Labels: enhancement

#45 change Metadata
  src/app/layout.tsx
Labels: enhancement

#47 Improve spacing in Message List component
  src/app/editor/components/message-list.tsx
Labels: bug, enhancement

#48 Improve File Management UI: Distinct Identification and Human-Readable Timestamps
  src/app/file-list/page.tsx
Labels: enhancement

#51 Create a page to display the list of fine-tuning jobs
  src/app/job-list/page.tsx
Labels: enhancement

#49 Create a page to Enter OpenAI API Key
  src/app/file-list/page.tsx
  src/components/input-api-key.tsx
  src/utils/openai.ts
Labels: enhancement

#56 Implement GitHub Actions Workflow for Auto-Merging Main to Debug Branch or Creating PR
  .github/workflows/merge-to-debug.yml
Labels: CI/CD

#58 Explicitly checkout debug branch from origin in GitHub Actions Workflow
  .github/workflows/merge-to-debug.yml
Labels: bug, CI/CD

#62 Add Docker and docker-compose configuration
  .github/workflows/docker-compose-validate.yml
  .github/workflows/docker-lint.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement, CI/CD

#59 Add mechanism to pass stored API key from local storage to each page
  src/app/editor/containers/editor-page.tsx
  src/app/file-list/page.tsx
  src/app/job-list/page.tsx
Labels: enhancement

#67 Add Build-Only Workflow for Additional Validation Before Merge
  .github/workflows/gh-pages-trial.yml
Labels: enhancement, CI/CD

#64 bugfix/resolve-merge-conflicts-better
  .github/workflows/merge-to-debug.yml
Labels: bug, enhancement, CI/CD

#70 Enhance permissions for merge-to-debug workflow to support pull-request operations
  .github/workflows/merge-to-debug.yml
Labels: bug, CI/CD

#60 Create a button to start fine-tuning
  src/app/file-list/page.tsx
Labels: enhancement

#71 EditorPageContainer: Manage API Key State with useEffect
  src/app/editor/containers/editor-page.tsx
Labels: bug

#74 Enhance GitHub Workflow to Distinguish PRs Based on Merge Commits and Conflicts
  .github/workflows/merge-to-debug.yml
Labels: bug, CI/CD

#78 Correction Needed: Use 'main' instead of 'merge-main-to-debug' as PR head
  .github/workflows/merge-to-debug.yml
Labels: bug, CI/CD

#81 Revert "Delete src/components/SessionStorageViewer.tsx"
  src/components/SessionStorageViewer.tsx
Labels: enhancement

#87 [README] Add status badges
  README.md
Labels: documentation, enhancement

#95 [Loading Components] Add Dark Mode Capability
  src/components/loading.tsx
Labels: enhancement

#102 [MessageList] Enhance bottom spacing for improved visuals
  src/app/editor/components/message-list.tsx
Labels: enhancement

#113 [home] Add `api-key-form`
  src/app/page.tsx
Labels: enhancement

#117 [api-key-form] improve UI
  src/components/api-key-form.tsx
Labels: enhancement

#123 [api-key-form] Refactor handleInputChange to accept string value directly
  src/components/api-key-form.tsx
Labels: enhancement

#125 [api-key-form] Implement Container-Presentational Pattern
  src/app/page.tsx
  src/components/api-key-form.tsx
  src/containers/api-key-form.tsx
Labels: enhancement

#127 [api-key-form] Add notice and link in api-key-form for accessing Editor without API key
  src/components/api-key-form.tsx
Labels: enhancement

#130 [api-key-form] Implement redirection to file-list page after submitting API key
  src/containers/api-key-form.tsx
Labels: enhancement

#133 [dependency] Downgrade Next.js to 13.4.19
  package.json
  pnpm-lock.yaml
  src/app/editor/[id]/components/specific-file-editor-page.tsx
  src/app/editor/[id]/containers/specific-file-editor-page.tsx
  src/app/editor/[id]/page.tsx
Labels: enhancement

#136 [specific-file-editor-page.tsx] Incorrect useParams type parameter
  src/app/editor/[id]/containers/specific-file-editor-page.tsx
Labels: bug

#138 add dependabot
  .github/dependabot.yml
Labels: enhancement, CI/CD

#153 Add support for Docker
  .github/dependabot.yml
Labels: enhancement, CI/CD

#155 Add support for GitHub Actions
  .github/dependabot.yml
Labels: enhancement, CI/CD

#145 [workflows] remove unnecessary command
  .github/workflows/gh-pages-trial.yml
  .github/workflows/gh-pages.yml
Labels: CI/CD

#157 [editor] Improvement in Logic for Disabling Upload Button
  src/app/editor/containers/editor-page.tsx
Labels: bug

#162 Add Prettier Formatting Check to GitHub Workflows
  .github/workflows/lint.yml
Labels: enhancement, CI/CD

#167 Use Query Parameters for Dynamic Routing
  src/app/editor/[id]/components/specific-file-editor-page.tsx
  src/app/editor/[id]/containers/specific-file-editor-page.tsx
  src/app/editor/[id]/page.tsx
  src/app/editor/containers/editor-page.tsx
  src/app/editor/containers/specific-file-editor-page.tsx
  src/app/editor/page.tsx
Labels: enhancement

#168 [file-list] Link to Editor Page
  src/app/file-list/page.tsx
Labels: enhancement

#170 [file-list] Improve UI
  src/app/file-list/page.tsx
Labels: enhancement

#175 [file-list] Remove Column
  src/app/file-list/page.tsx
Labels: enhancement

#178 Add Material Symbols
  package.json
  pnpm-lock.yaml
Labels: dependencies

#184 [file-list] Add Play Arrow Icon
  src/app/file-list/page.tsx
  src/app/file-list/styles.module.css
Labels: enhancement

#188 [file-list] Change Column Header Title
  src/app/file-list/page.tsx
Labels: enhancement

#199 [dependabot] add reviewer
  .github/dependabot.yml
Labels: CI/CD

#202 Setup Unit Testing Framework
  jest.config.js
  package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies

#208 [home] add test
  tests/src/app/page.test.tsx
Labels: enhancement

#209 Run tests before committing
  lint-staged.config.js
Labels: enhancement

#210 Add test for CI
  .github/workflows/lint.yml
  package.json
Labels: enhancement

#212 Add Codecov badge
  README.md
Labels: documentation

#216 Add devDependencies: @testing-library/user-event
  package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies

#218 Extend Jest with custom matchers
  jest.config.js
  jest.setup.js
Labels: enhancement
